using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using TPF.Internal;

namespace TPF.Controls.Specialized.TaskBoard
{
    public class TaskBoardColumnCollection : ObservableCollection<TaskBoardColumn>
    {
        public TaskBoardColumnCollection() { }

        public TaskBoardColumnCollection(IEnumerable<TaskBoardColumn> columns) : base(columns) { }

        public TaskBoardColumnCollection(List<TaskBoardColumn> columns) : base(columns) { }

        public TaskBoardColumn GetColumnFromValue(object value)
        {
            return this.FirstOrDefault(x => ValueComparer.IsEqualTo(x.Value, value));
        }

        public void ClearColumns()
        {
            for (int i = 0; i < Count; i++)
            {
                var column = this[i];

                column.Items.Clear();
            }
        }

        internal void DeleteAutoGeneratedColumns()
        {
            for (int i = Count - 1; i >= 0; i--)
            {
                var column = this[i];

                if (column.IsAutoGenerated)
                {
                    column.Items.Clear();
                    Remove(column);
                }
            }
        }
    }
}